image: node:8-alpine

before_script:
  - npm install

cache:
  paths:
  - node_modules/

jest:
  script:
    - npm run coverage
  tags:
    - node

eslint:
  script:
    - npm run lint
  tags:
    - node
